### ISSUE TITLE
einops.reduce behavior for list input

### ISSUE THREAD

**Issue by ferrophile** [arogozhnikov/einops#172]
`reduce` seems to not accept list of equal-shaped tensors as input - even though the [API](https://einops.rocks/api/reduce/) claims it should. (Just for comparison, `rearrange` appears to work as expected).

```
>>> import einops
>>> import numpy as np
>>> a = np.random.rand(3, 4)
>>> b = np.random.rand(3, 4)
>>> out1 = einops.rearrange([a, b], 'i j k -> j i k')
>>> out1.shape
(3, 2, 4)
>>> out2 = einops.reduce([a, b], 'i j k -> j k', 'sum')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hwpang/miniconda3/envs/nerf-pytorch/lib/python3.7/site-packages/einops/einops.py", line 409, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/home/hwpang/miniconda3/envs/nerf-pytorch/lib/python3.7/site-packages/einops/einops.py", line 230, in _apply_recipe
    backend = get_backend(tensor)
  File "/home/hwpang/miniconda3/envs/nerf-pytorch/lib/python3.7/site-packages/einops/_backends.py", line 52, in get_backend
    raise RuntimeError('Tensor type unknown to einops {}'.format(type(tensor)))
RuntimeError: Tensor type unknown to einops <class 'list'>
```
Is the above intended behavior?

**Comment by arogozhnikov** [comment]
> Is the above intended behavior?

Yes, for now it is intended.

I think that lists worked well and it feels safe to expand their support to reduce/repeat functions in the next version
