### ISSUE TITLE
[BUG] Ellipsis cannot be parsed

### ISSUE THREAD

**Issue by francois-rozet** [arogozhnikov/einops#259]
**Describe the bug**

It seems like ellipsis cannot be parsed. The backend does not matter as it fails at the recipe.

**Reproduction steps**

```python
>>> import numpy
>>> import einops
>>> x = numpy.arange(12)
>>> einops.rearrange(x, '... -> ...')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../miniconda3/envs/jax/lib/python3.9/site-packages/einops/einops.py", line 483, in rearrange
    return reduce(cast(Tensor, tensor), pattern, reduction='rearrange', **axes_lengths)
  File ".../miniconda3/envs/jax/lib/python3.9/site-packages/einops/einops.py", line 411, in reduce
    recipe = _prepare_transformation_recipe(pattern, reduction, axes_lengths=hashable_axes_lengths)
  File ".../miniconda3/envs/jax/lib/python3.9/site-packages/einops/einops.py", line 258, in _prepare_transformation_recipe
    if left.has_ellipsis and left._apply_recipehas_ellipsis_parenthesized:
AttributeError: 'ParsedExpression' object has no attribute '_apply_recipehas_ellipsis_parenthesized'
```

**Your platform**

Python 3.9.16, Ubuntu 23.04, NumPy 1.24.3

**Comment by arogozhnikov** [comment]
Your version is broken. For reference, that's how this line should look like in einops

https://github.com/arogozhnikov/einops/blob/230ac1526c1f42c9e1f7373912c7f8047496df11/einops/einops.py#LL258C45-L258C45

**Comment by francois-rozet** [comment]
Yep, my bad, I realized almost immediately. Sorry for the inconvenience.
