### ISSUE TITLE
Add layers for tf and tf.keras

### ISSUE THREAD

**Issue by arogozhnikov** [arogozhnikov/einops#27]
Continuing discussion started in pull-request #25 .

So far: `tf.keras` и `keras` are different things now, they work on different input and have different recommendations for creating custom layers.

This version seems to work for me with tensorflow.

```python
import tensorflow as tf
from einops.layers.keras import RearrangeMixin, ReduceMixin, UnknownSize

class Rearrange(RearrangeMixin, tf.keras.layers.Layer):
    def call(self, inputs):
        return self._apply_recipe(inputs)
    
class Reduce(ReduceMixin, tf.keras.layers.Layer):
    def call(self, inputs):
        return self._apply_recipe(inputs)    
```

Example for eager execution
```python
tf.enable_eager_execution()

x = tf.zeros([4, 5], dtype='float32')
Rearrange('i j -> j i')(x).shape
Reduce('i j -> j', 'max')(x).shape
```

And example without eager execution

```python
import numpy
x = tf.placeholder('float32')
x.set_shape([None, None])
with tf.Session().as_default():
    y = Rearrange('i j -> j i')(x).eval({x: numpy.zeros([5, 6], dtype='float32')})
    y = Reduce('i j -> j', 'max')(x).eval({x: numpy.zeros([5, 6], dtype='float32')})
```

At least this seems to comply with tf guide 
https://www.tensorflow.org/tutorials/eager/custom_layers

My env:

```python
python 3.6 (should not affect)
In [2]: tensorflow.__version__
Out[2]: '1.10.0'
In [4]: keras.__version__ (should not affect)
Out[4]: '2.2.4'
```

**Comment by adam-r-kowalski** [comment]
```
# %% imports
import tensorflow as tf
from einops.layers import RearrangeMixin, ReduceMixin

# %% layers
layers = tf.keras.layers

# %% rearrange
class Rearrange(RearrangeMixin, layers.Layer):
    def call(self, inputs):
        return self._apply_recipe(inputs)

# %% reduce
class Reduce(ReduceMixin, layers.Layer):
    def call(self, inputs):
        return self._apply_recipe(inputs)

# %% model
model = tf.keras.Sequential([
    Rearrange("b c h w -> b (c h w)")
])

# %% sample data
data = tf.random.normal((50, 3, 250, 250))

# %% session
session = tf.Session()

session.run(model(data))
```

This throws an exception

```
Traceback (most recent call last):
  File "demo.py", line 29, in <module>
    session.run(model(data))
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 224, in build
    shape = layer.compute_output_shape(shape)
  File "/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1016, in compute_output_shape
    raise NotImplementedError
NotImplementedError
```

**Comment by adam-r-kowalski** [comment]
With the changes that I proposed in the pull request this issue goes away. The updated README.md shows how to translate from the PyTorch code to equivalent TensorFlow code

**Comment by arogozhnikov** [comment]
Hi, sorry for delay.

tf.keras indeed requires computing output_shape, so I've merged your PR.

- I think we also need to add custom objects so that `keras` models to save and load models from hdf5.
- and tests also needed for new backend
